import { Footer, MainHeader } from '@/components';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/tailwind.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Studio Page',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<MainHeader />
				{children}
				<Footer />
			</body>
		</html>
	);
}
